#
# Blog Settings
#
name: Ahmed Kamal
description:
url: http://ahmedkamal.github.io/
title: Ahmed Kamal
subtitle:  Learning With Passion
gravatar_url: https://en.gravatar.com/userimage/29648221/8807968df1965e8cac2c75a2ec55a8c4.jpg
subscribe_rss: http://feeds.feedburner.com/AhmedKamalBlog
encoding: utf-8

# Github repositories
github_user: AhmedKamal
github_repo_url: https://github.com/AhmedKamal/ahmedkamal.github.io

# Twitter
twitter_user: A7med_Kamal
twitter_tweet_button: true


# Disqus Comments
disqus_short_name: ahmedkamal
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-51102645-1
google_analytics_domain: http://ahmedkamal.github.io


#
# Jekyll Settings
#
markdown: redcarpet
pygments: true
permalink: /:year/:month/:title.html
paginate: 20
paginate_path: "page/:num"
category_dir: categories
